apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-query
  namespace: mysql-query
spec:
  selector:
    matchLabels:
      run: mysql-query
  replicas: 2
  template:
    metadata:
      labels:
        run: mysql-query
    spec:
      containers:
      - name: mysql-query
        image: xiang13225080/mysqldemo:demo
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_DSN
          value: "jdbc:mysql://192.168.31.24:3306/mysql"
        - name: MYSQL_USER
          value: "chaos"
        - name: MYSQL_PASSWORD
          value: "chaos-mesh"
        ports:
        - containerPort: 8001

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-query
  namespace: mysql-query
  labels:
    run: mysql-query
spec:
  type: NodePort
  ports:
  - port: 8001
    protocol: TCP
    nodePort: 30001
  selector:
    run: mysql-query